language: java
jdk: 
  - openjdk8
  
env: 
  - CODECOV_TOKEN='c7eff097-4d1c-4b64-9636-4e6fe80ce395'
  
script: 
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)